# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Target package to publish'
        required: true
        type: choice
        options:
        - "@yurychang/eslint-config"
        - "@yurychang/eslint-config-react"
        - "@yurychang/eslint-config-typescript"
        - "@yurychang/prettier-config"
      changing_type:
        description: 'type of version to increase'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          
      # - name: Git configuration
      #   run: |
      #     git config --global user.email "GitHub Actions"
      #     git config --global user.name "GitHub Actions"
      
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          
      - name: Increase version
        run: npm version $CHANGING_TYPE -m "[$PACKAGE] Release %s" --workspace $PACKAGE
        
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Publish package to npm
        run: npm publish --workspace $PACKAGE --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
