# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'target package'
        required: true
        type: choice
        options:
        - \@yurychang/eslint-config
        - \@yurychang/eslint-config-react
        - \@yurychang/eslint-config-typescript
        - \@yurychang/prettier-config

jobs:
  publish-npm:
    if: "contains(github.event.head_commit.message, '[eslint-config] v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Make the script files executable
        run: chmod +x get-release-version.sh
      - name: Get release version
        run: ./get-release-version.sh
        env:
          commit_message: ${{ github.event.head_commit.message }}
      - name: print
        run: echo $release_version
        env: 
          release_version: ${{ env.release_version }}
      - run: npm publish --workspace @yurychang/eslint-config --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.eslint_config_npm_token}}

