# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Target package to publish'
        required: true
        type: choice
        options:
        - "@yurychang/eslint-config"
        - "@yurychang/eslint-config-react"
        - "@yurychang/eslint-config-typescript"
        - "@yurychang/prettier-config"
      changing_type:
        description: 'type of version to increase'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      
      - name: Increase version & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          version=$(npm version $CHANGING_TYPE --workspace $PACKAGE | head -n 2| tail -1 | cut -d# -f2)
          git add .
          git commit -m "[$PACKAGE] $version"
          git push
        env:
          PACKAGE: ${{ inputs.PACKAGE }}
          CHANGING_TYPE: ${{ inputs.CHANGING_TYPE }}
        
      - name: Publish package to npm
        run: npm publish --workspace $PACKAGE --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          PACKAGE: ${{ inputs.PACKAGE }}
